                </div>
            </div>
            <div id="rodape">
                Os direitos cedidos a Claro SA 2015 - 
                <?php
                    $mk=time();
                    $ano=new conversaodata();
                    echo $ano->get_ano($mk);
                ?>
                 - Cluster Santa Catarina
                <a href="/sistemas/versoes" >  - <img src="/img/216.png" /> - Desenvolvedores </a>
            </div>
    </body>
</html>