<style>
		* { margin: 0; padding: 0; }

		#bg { position: fixed; top: 0; left: 0; }
		.bgwidth { width: 100%; }
		.bgheight { height: 100%; }

		#page-wrap { position: absolute; width: 950px;top: 250px; margin: 0px 30px; padding: 10px; background: white; -moz-box-shadow: 0 0 20px black; -webkit-box-shadow: 0 0 20px black; box-shadow: 0 0 20px black; }
                #page-quiz { position: relative; width: 50px; margin: 165px 150px; }
		p { font: 15px/2 Georgia, Serif; margin: 0 0 30px 0; text-indent: 40px; }
</style>
<body>
    <img src="/img/Fundo-Quiz.png" id="bg" alt="" width="100%" height="100%">
    <div id="page-quiz">
        <p><font  style="font-family:'Arial';color: #FFFFFF;font-size:40px;" ><b>Classificação</b></font></p>
    </div>
<div id="page-wrap">
    <table border="1" cellpadding="0" cellspacing="0" width="100%">
        <tr align="center" style="font-family:'Arial';color: #000000;font-size:18px;">
            <td>
                <b>NOME</b>
            </td>
            <td>
                <b>IDADE</b>
            </td>
            <td>
                <b>ACERTOS</b>
            </td>
            <td>
                <b>TEMPO</b>
            </td>

        </tr>
<?php
        $quiz=new quiz();
        $quiz->hiscore();
?>
    </table>
    <p>
    <?php
    echo $quiz->cabec_botao('inicio','');        
    $form=$quiz->end_form('voltar ao inicio');
    echo $form;
    ?>
    </p>
</div>
<style type="text/css" style="display: none !important;">
	* {
		margin: 0;
		padding: 0;
	}
	body {
		overflow-x: hidden;
	}
	#demo-top-bar {
		text-align: left;
		background: #222;
		position: relative;
		zoom: 1;
		width: 100% !important;
		z-index: 6000;
		padding: 20px 0 20px;
	}
	#demo-bar-inside {
		width: 960px;
		margin: 0 auto;
		position: relative;
		overflow: hidden;
	}
	#demo-bar-buttons {
		padding-top: 10px;
		float: right;
	}
	#demo-bar-buttons a {
		font-size: 12px;
		margin-left: 20px;
		color: white;
		margin: 2px 0;
		text-decoration: none;
		font: 14px "Lucida Grande", Sans-Serif !important;
	}
	#demo-bar-buttons a:hover,
	#demo-bar-buttons a:focus {
		text-decoration: underline;
	}
	#demo-bar-badge {
		display: inline-block;
		width: 302px;
		padding: 0 !important;
		margin: 0 !important;
		background-color: transparent !important;
	}
	#demo-bar-badge a {
		display: block;
		width: 100%;
		height: 38px;
		border-radius: 0;
		bottom: auto;
		margin: 0;
		background: url(/images/examples-logo.png) no-repeat;
		background-size: 100%;
		overflow: hidden;
		text-indent: -9999px;
	}
	#demo-bar-badge:before, #demo-bar-badge:after {
		display: none !important;
	}
</style>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="f617b25778b2c492fa95db23-|49" defer=""></script></body>
</html>