<style>
    .images {
        background-image: url(/img/fundo.png);
        bac
        width:  100%;
        height: 100%;
        background-repeat: repeat;
        background-attachment: fixed;

    }
    H1{
        font-family: arial;
        font-size: 30px;
        font-weight: bold;
        color: #ffffff;
        padding-bottom: 2px;
    }
    h2 {
        font-family: arial;
        font-size: 24px;
        font-weight: bold;
        color: #ffffff;
        padding-top: 0px;
        padding-bottom: 0px;
    }
</style>
<body  bgcolor="#752995">
    <table cellpadding="0" cellspacing="0" border="0" width="100%" heigth="100%">
        <tr heigth="200px">
            <td colspan="2" align="center" class="images">
                <br />
                <br />
                <br />
                <h1>SEJA BEM-VINDO</h1><br />
                <H2><font color=yellow><b>CLIQUE</b></font> EM UM DOS JOGOS PARA COMEÇAR </H2><br />
                <H2>E TESTE SEU CONHECIMENTO</H2><br />
                <br />
                <br />
                <br />
            </td>
        </tr>
        <tr>
            <td width="50%">
                <a href="/index/quiz"><img src="/img/quiz.png"  width="100%" height="100%"></a>
            </td>
            <td width="50%">
                <a href="/memoria"><img src="/img/jogo-da-memoria.png"  width="100%" height="100%"></a>
            </td>            
        </tr>            
        <tr >
            <td colspan="2" align="center" class="images">
                <br />
                <a href="/index/c"><h1>Classificação</h1></a>
                <br />
            </td>
        </tr>
    </table>
</body>
