<style>
		* { margin: 0; padding: 0; }

		#bg { position: fixed; top: 0; left: 0; }
		.bgwidth { width: 100%; }
		.bgheight { height: 100%; }

		#page-wrap { position: relative; width: 650px; margin: 50px auto; padding: 20px; background: white; -moz-box-shadow: 0 0 20px black; -webkit-box-shadow: 0 0 20px black; box-shadow: 0 0 20px black; }
		p { font: 15px/2 Georgia, Serif; margin: 0 0 30px 0; text-indent: 40px; }
</style>
<script type="text/javascript">
function validaCampo(){
    
    if(document.quiz2.joke.value==""){
	alert("Informe o nome !");
	return false;
    } else {
        alert(document.quiz2.joke.value);
        return true;
    }
}
</script>
<body>
    <img src="/img/Fundo-Quiz.png" id="bg" alt="" width="100%" height="100%">
<div id="page-wrap"
    <?php
        $database=new db();
        $quiz=new quiz();
     if(!isset($_POST['nome_jogador'])){
         echo "<p align=center ><h1 ><font color=red>NÃO TENTE TRAPASSEAR ...</font> <br />Você precisa seguir as Regras !!!</h1>";
         echo "Clique <a  href='/index/quiz'> Aqui para retornar ao inicio </a>";
     } else {
        $perguntas=$quiz->lista_perguntas();
        $total=$quiz->conta_pergunta($perguntas);
        if($_POST['nome_jogador']!="" AND !isset($_POST['id_pergunta'])) {
            $id_pergunta=1;
            $tempo_i=time();
            $query="INSERT INTO `andamento` (`id`, `nome_jogador`, `idade_jogador`, `time_inicio`, `time_fim`, `resposta_1`, `resposta_2`, `resposta_3`, `resposta_4`, `resposta_5`, `resposta_6`, `resposta_7`, `resposta_8`, `resposta_9`, `resposta_10`, `resposta_11`, `resposta_12`, `resposta_13`, `resposta_14`, `resposta_15`) VALUES ('', '".$_POST['nome_jogador']."', '".$_POST['idade_jogador']."', '".$tempo_i."', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');";
            $database->query($query);
            $result=$database->execute();
            $time=$_POST['max_time'];
        }
        if($_POST['nome_jogador']!="" AND isset($_POST['id_pergunta'])) {
            $id_pergunta=$_POST['id_pergunta'];
            $tempo_i=$_POST['tempo_i'];
            $resposta=$_POST['joke'];
            $tempo_a=time();
            $query="UPDATE `andamento` SET `time_fim` = '".$tempo_a."', `resposta_".$id_pergunta."` = '".$resposta."'  WHERE `nome_jogador` like '".$_POST['nome_jogador']."' and `idade_jogador` = ".$_POST['idade_jogador']." and time_inicio = ".$tempo_i.";";
            $database->query($query);
            $result=$database->execute();
            $time=$_POST['max_time'];
            $tempo=$tempo_a-$tempo_i;
            $tempo_max=60*$time;
            if( $tempo_max > $tempo ) {  
                $id_pergunta=$id_pergunta+1;
            } else {
                $id_pergunta=$total+1;
                $info="end";
            }

        }        
  

        if ($id_pergunta<=$total){
            echo "<p>Pegunta $id_pergunta / $total :";
            $pergunta=$quiz->lista_pergunta($id_pergunta);
            echo $quiz->cabec_botao('quiz2',$id_pergunta);        
            $perguntas=$quiz->monta_pergunta($pergunta); 
            $quiz->monta_inicio('hidden','nome_jogador',$_POST['nome_jogador'],'0'); 
            $quiz->monta_inicio('hidden','idade_jogador',$_POST['idade_jogador'],'0'); 
            $quiz->monta_inicio('hidden','tempo_i',$tempo_i,'0');
            $quiz->monta_inicio('hidden','id_pergunta',$id_pergunta,'0');
            $quiz->monta_inicio('hidden','max_time',$time,'0');             
            echo "</p>    ";
            $form=$quiz->end_form('Enviar');
    echo $form;
        } else {
            
            if(isset($info)) {
                echo "<p><h1 align=center >".$_POST['nome_jogador'].", <br><font color=red>O tempo para a conclusão do quiz acabou!!!</font> </h1>";
                echo "<br><p align=center><img src=\"/img/erro2.gif\" width=\"55%\" align=\"center\">";
            } else {
                echo "<p><h1 align=center > Parabéns, ".$_POST['nome_jogador'].", <br><font color=red>Você concluiu o quiz!!!</font></h1>";
                echo "<p align=center><img src=\"/img/concluido.gif\" width=\"30%\" align=\"center\"><img src=\"/img/concluido2.gif\" width=\"55%\" align=\"center\">";
            }
            $respostas=$quiz->consulta_respostas($_POST['nome_jogador'],$_POST['idade_jogador'],$tempo_i,$total);
            $corretas=$quiz->consulta_corretas();
            $acertos=$quiz->compara($respostas, $corretas, $total);
            echo "<p><h2 align='center'> Acertou ".$acertos." / ".$total."</h2>";
            $tempodb=($tempo_a-$tempo_i);
            $decorrido=($tempo_a-$tempo_i)/60;
            $minutos=number_format($decorrido, 0, '', '');
            $segundos=($decorrido-$minutos)*60;
            $query="INSERT INTO `hiscore` (`id`, `name`, `idade`,`time`, `acertos`, `tempo_exec`) VALUES (NULL, '".$_POST['nome_jogador']."', '".$_POST['idade_jogador']."', '".$tempo_a."', '".$acertos."', '".$tempodb."');";
            #echo "<p>".$query;
            $database->query($query);
            $result=$database->execute();           
            echo "<p><h2 align='center' > Em um tempo de ".$minutos." minutos e ".$segundos." segundos.";
            echo "<p><h2 align='center'><a href='/index/hiscores' >Clique aqui para ver os maiores pontuadores</a></h2>";
            echo "<p>";
            echo $quiz->cabec_botao('inicio','');        
            $form=$quiz->end_form('voltar ao inicio');
            echo $form;
            echo "</p>";
        }
    ?>

     <?php
     }
     ?>
</div>
<style type="text/css" style="display: none !important;">
	* {
		margin: 0;
		padding: 0;
	}
	body {
		overflow-x: hidden;
	}
	#demo-top-bar {
		text-align: left;
		background: #222;
		position: relative;
		zoom: 1;
		width: 100% !important;
		z-index: 6000;
		padding: 20px 0 20px;
	}
	#demo-bar-inside {
		width: 960px;
		margin: 0 auto;
		position: relative;
		overflow: hidden;
	}
	#demo-bar-buttons {
		padding-top: 10px;
		float: right;
	}
	#demo-bar-buttons a {
		font-size: 12px;
		margin-left: 20px;
		color: white;
		margin: 2px 0;
		text-decoration: none;
		font: 14px "Lucida Grande", Sans-Serif !important;
	}
	#demo-bar-buttons a:hover,
	#demo-bar-buttons a:focus {
		text-decoration: underline;
	}
	#demo-bar-badge {
		display: inline-block;
		width: 302px;
		padding: 0 !important;
		margin: 0 !important;
		background-color: transparent !important;
	}
	#demo-bar-badge a {
		display: block;
		width: 100%;
		height: 38px;
		border-radius: 0;
		bottom: auto;
		margin: 0;
		background: url(/images/examples-logo.png) no-repeat;
		background-size: 100%;
		overflow: hidden;
		text-indent: -9999px;
	}
	#demo-bar-badge:before, #demo-bar-badge:after {
		display: none !important;
	}
</style>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="f617b25778b2c492fa95db23-|49" defer=""></script></body>
</html>