<style>
		* { margin: 0; padding: 0; }

		#bg { position: fixed; top: 0; left: 0; }
		.bgwidth { width: 100%; }
		.bgheight { height: 100%; }

		#page-wrap { position: relative; width: 650px; margin: 50px auto; padding: 20px; background: white; -moz-box-shadow: 0 0 20px black; -webkit-box-shadow: 0 0 20px black; box-shadow: 0 0 20px black; }
		p { font: 15px/2 Georgia, Serif; margin: 0 0 30px 0; text-indent: 40px; }
</style>
<?php
$time=10;
?>
<script type="text/javascript">
function validaCampo(){
if(document.quiz2.nome_jogador.value==""){
	alert("Informe o nome !");
	return false;
} else if(document.quiz2.idade_jogador.value==""){
	alert("Informe a Idade !");
	return false;
} else return true;
}
</script>
<body>
    <img src="/img/Fundo-Quiz.png" id="bg" alt="" width="100%" height="100%">
<div id="page-wrap"
     <p><h1 align="center" > Vamos começar o jogo? </h1></p>
<p> Mas, para isso precisamos informar: há única regra. É preciso responder todas as perguntas dentro do limite de tempo de <b><?php echo "$time"; ?> minutos</b>.
        <br>O tempo começará a contar a partir do inicio da primeira pergunta.
    
     <?php
    $db=new db();
    $quiz=new quiz();
    echo $quiz->cabec_com('quiz2');
    echo "<p> <b>Nome :</b>";
    $quiz->monta_inicio('text','nome_jogador',null,'1'); 
    echo "<p> <b>Idade : </b>";
    $quiz->monta_inicio('text','idade_jogador',null,'1'); 
    #echo "<p> <b>Digite seu campus : </b>";
    $quiz->monta_inicio('hidden','max_time',$time,'0'); 
    echo "<p> ";
    $form=$quiz->end_form('Enviar');
    echo $form;
    
    ?>
</p>

</div>
<style type="text/css" style="display: none !important;">
	* {
		margin: 0;
		padding: 0;
	}
	body {
		overflow-x: hidden;
	}
	#demo-top-bar {
		text-align: left;
		background: #222;
		position: relative;
		zoom: 1;
		width: 100% !important;
		z-index: 6000;
		padding: 20px 0 20px;
	}
	#demo-bar-inside {
		width: 960px;
		margin: 0 auto;
		position: relative;
		overflow: hidden;
	}
	#demo-bar-buttons {
		padding-top: 10px;
		float: right;
	}
	#demo-bar-buttons a {
		font-size: 12px;
		margin-left: 20px;
		color: white;
		margin: 2px 0;
		text-decoration: none;
		font: 14px "Lucida Grande", Sans-Serif !important;
	}
	#demo-bar-buttons a:hover,
	#demo-bar-buttons a:focus {
		text-decoration: underline;
	}
	#demo-bar-badge {
		display: inline-block;
		width: 302px;
		padding: 0 !important;
		margin: 0 !important;
		background-color: transparent !important;
	}
	#demo-bar-badge a {
		display: block;
		width: 100%;
		height: 38px;
		border-radius: 0;
		bottom: auto;
		margin: 0;
		background: url(/images/examples-logo.png) no-repeat;
		background-size: 100%;
		overflow: hidden;
		text-indent: -9999px;
	}
	#demo-bar-badge:before, #demo-bar-badge:after {
		display: none !important;
	}
</style>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="f617b25778b2c492fa95db23-|49" defer=""></script></body>
</html>